<?php

namespace Brace\Mod\Request\Zend;

use Laminas\Diactoros\Response;
use Psr\Http\Message\ResponseInterface;

class StreamedResponse extends Response
{
    
    public function __construct(protected Closure $callback, protected int $code = 200, protected array $headers = [])
    {
        
    }

    /**
     * Called by StreamedResponseEmitter::emit()
     * 
     * Output should be generated by the Callback directly.
     * 
     * @return void
     */
    public function __emit()
    {
       
        ($this->callback)();
        
    }

}
