<?php

namespace Brace\Mod\Request\Zend;

use Laminas\Diactoros\Response;
use Psr\Http\Message\ResponseInterface;

class StreamedResponse extends Response
{

    public function __construct(protected \Closure $callback,  int $code = 200, array $headers = [])
    {
        parent::__construct('php://temp', $code, $headers);
    }

    /**
     * Called by StreamedResponseEmitter::emit()
     *
     * Output should be generated by the Callback directly.
     *
     * @return void
     */
    public function __emit()
    {

        ($this->callback)();

    }

}
